version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flight_booking
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/flight_booking -user=postgres -password=123456 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
  redis:
    image: redis:latest
    ports:
      - 6379:6379